Update from upstream

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,3 +1,6 @@
+variables:
+  system.debug: true
+
 jobs:
 
 - job: build_jdk
@@ -39,16 +42,24 @@ jobs:
     displayName: show environment
   - bash: |
       set -ex
+      if [ -d /tmp/$USER/git-scripts ]; \
+        then git -C /tmp/$USER/git-scripts pull -q > /dev/null 2>&1 ; \
+        else mkdir -p /tmp/$USER && git -C /tmp/$USER clone --filter=blob:none -q https://github.com/plume-lib/git-scripts.git ; \
+      fi
+    displayName: git-scripts
+  - bash: |
+      set -ex
       if [ -d /tmp/$USER/plume-scripts ]; \
         then git -C /tmp/$USER/plume-scripts pull -q > /dev/null 2>&1 ; \
-        else mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git ; \
+        else mkdir -p /tmp/$USER && git -C /tmp/$USER clone --filter=blob:none -q https://github.com/plume-lib/plume-scripts.git ; \
       fi
     displayName: plume-scripts
   # This creates ../jdk17u .
-  # If the depth is too small, the merge will fail.
+  # If the depth is too small, the merge will fail.  However, we cannot use "--filter=blob:none"
+  # because that leads to "fatal: remote error: filter 'combine' not supported".
   - bash: |
       set -ex
-      /tmp/$USER/plume-scripts/git-clone-related typetools jdk17u ../jdk17u -q --depth 999
+      /tmp/$USER/git-scripts/git-clone-related typetools jdk17u ../jdk17u -q --depth 999
     displayName: clone-related-jdk17u
   - bash: |
       set -ex
@@ -76,16 +87,16 @@ jobs:
   #   displayName: make run-test
 
 - job: test_cftests_all_jdk11
-  timeoutInMinutes: 105
+  timeoutInMinutes: 120
   pool:
     vmImage: 'ubuntu-latest'
   container: mdernst/cf-ubuntu-jdk11:latest
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
-    displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --filter=blob:none -q https://github.com/plume-lib/git-scripts.git
+    displayName: clone git-scripts
+  - bash: /tmp/$USER/git-scripts/git-clone-related typetools checker-framework
     displayName: clone checker-framework
 # test-cftests-all.sh sometimes runs out of memory, but running its component parts in sequence does not.
 #   - bash: (cd ../checker-framework && checker/bin-devel/test-cftests-all.sh)
@@ -108,31 +119,31 @@ jobs:
 #     displayName: publish all.tgz
 
 - job: test_cftests_all_jdk17
-  timeoutInMinutes: 105
+  timeoutInMinutes: 120
   pool:
     vmImage: 'ubuntu-latest'
   container: mdernst/cf-ubuntu-jdk17:latest
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
-    displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --filter=blob:none -q https://github.com/plume-lib/git-scripts.git
+    displayName: clone git-scripts
+  - bash: /tmp/$USER/git-scripts/git-clone-related typetools checker-framework
     displayName: clone checker-framework
   - bash: (cd ../checker-framework && checker/bin-devel/test-cftests-all.sh)
     displayName: test-cftests-all.sh
 
-- job: test_cftests_all_jdk19
-  timeoutInMinutes: 105
+- job: test_cftests_all_jdk20
+  timeoutInMinutes: 120
   pool:
     vmImage: 'ubuntu-latest'
-  container: mdernst/cf-ubuntu-jdk19:latest
+  container: mdernst/cf-ubuntu-jdk20:latest
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
-    displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --filter=blob:none -q https://github.com/plume-lib/git-scripts.git
+    displayName: clone git-scripts
+  - bash: /tmp/$USER/git-scripts/git-clone-related typetools checker-framework
     displayName: clone checker-framework
   - bash: (cd ../checker-framework && checker/bin-devel/test-cftests-all.sh)
     displayName: test-cftests-all.sh
@@ -145,9 +156,9 @@ jobs:
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
-    displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --filter=blob:none -q https://github.com/plume-lib/git-scripts.git
+    displayName: clone git-scripts
+  - bash: /tmp/$USER/git-scripts/git-clone-related typetools checker-framework
     displayName: clone checker-framework
   - bash: (cd ../checker-framework && checker/bin-devel/test-daikon.sh)
     displayName: test-daikon.sh
@@ -159,9 +170,9 @@ jobs:
   steps:
   - checkout: self
     fetchDepth: 25
-  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
-    displayName: clone plume-scripts
-  - bash: /tmp/$USER/plume-scripts/git-clone-related typetools checker-framework
+  - bash: mkdir -p /tmp/$USER && git -C /tmp/$USER clone --filter=blob:none -q https://github.com/plume-lib/git-scripts.git
+    displayName: clone git-scripts
+  - bash: /tmp/$USER/git-scripts/git-clone-related typetools checker-framework
     displayName: clone checker-framework
   - bash: (cd ../checker-framework && checker/bin-devel/test-plume-lib.sh)
     displayName: test-plume-lib.sh
